---
name: vhs

on:
  push:
    paths:
      - docs/demo.tape

jobs:
  vhs:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.10.5]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
        with:
          os: ${{ matrix.os }}
          python-version: ${{ matrix.python-version }}

      - name: Install pman with pipx
        run: pipx install .

      - uses: charmbracelet/vhs-action@v1
        with:
          path: docs/demo.tape

      - uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: Update generated VHS GIF
          branch: main
          commit_user_name: vhs-action 📼
          commit_user_email: actions@github.com
          commit_author: vhs-action 📼 <actions@github.com>
          file_pattern: docs/*.gif
